### ISSUE TITLE
How can I get this function from LazyArray

### ISSUE THREAD

**Issue by yangguohao** [jcmgray/autoray#12]
```
from autoray.lazy import Variable
from autoray import numpy as np
a = Variable(shape=(2,))
b = Variable(shape=(2,))
d = np.where(a>1, b, 1)
fn = d.get_function((a, b))
x = np.asarray([0.5, 3])
y = np.asarray([0.2, 1.5])
print(fn((x, y)))
```
line 44, in <module>
    fn = d.get_function((a, b))
AttributeError: 'numpy.ndarray' object has no attribute 'get_function'

How can I use the np.where to the LazyArray and get the function to the real array

**Comment by jcmgray** [comment]
I don't get the same error (`np.where(a>1, b, 1)` fails)? but the problem will be that two main functions are not implemented in `autoray.lazy.core.py` yet:
- `a > 1` i.e. `LazyArray.__gt__`
- `where` for `LazyArray` objects.
It should be very easy to add these, the only detail is computing the broadcasted shapes. Would be happy to accept a PR with these!

**Comment by yangguohao** [comment]
Thanks, I have register the new function 'where' for `autoray.lazy`.

**Comment by yangguohao** [comment]
By the way, I have found a mistake about `sum` function the autoray.lazy

**Comment by yangguohao** [comment]
By the way, there is a mistake of `reduction_func` function for `autoray.lazy`, 
![image](https://user-images.githubusercontent.com/70266361/219299144-0074c425-c168-45ba-a5bd-697ca7d271a6.png)
the axis should be (nd+(i+1)) if i < 0 for `sum` reduction?

**Comment by jcmgray** [comment]
Yes, or that should be ``nd + i`` I think. (e.g. for ndim=4, axis=-1 == axis=3). Thanks for spotting.

**Comment by yangguohao** [comment]
Cool. I will open a new PR for this issues, and further discuss about it.

**Comment by jcmgray** [comment]
The axis bug at least was fixed here: https://github.com/jcmgray/autoray/commit/5602e348968ad3cc72a477f660ed7253ab997036, by the way.
