### ISSUE TITLE
Full `jax.scipy` support

### ISSUE THREAD

**Issue by HaoTy** [jcmgray/autoray#17]
Currently, autoray defaults "jax" to "jax.numpy", with only a few functions explicitly aliased from other submodules. This makes many functions not in `jax.numpy`, such as `jax.scipy.fft.fft()`, inaccessible unless registered manually. Adding `_SUBMODULE_ALIASES["jax", "scipy.fft.fft"] = "jax.scipy.fft"` for each function works but I wonder if there's a more elegant solution.

**Comment by jcmgray** [comment]
Hi @HaoTy, yes I _think_ this should be as simple as adding:
```python
_MODULE_ALIASES["jax.scipy"] = "jax.scipy"
```
in the jax section in `autoray.py`. I would happily add this or accept a PR if you want to test it out and contribute.

**Comment by HaoTy** [comment]
#18 My pleasure! I was about to say it wouldn't work as it was the first thing I tried, but realized it should be inserted into the dict before "jax.numpy".

**Comment by jcmgray** [comment]
Closed by #18.
